apiVersion: v1
kind: Namespace
metadata:
  name: finetrace


---


apiVersion: v1
kind: ConfigMap
metadata:
  namespace: finetrace
  name: webui-configmap
data:
  SPRING_PROFILES_ACTIVE: dev
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8 -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Duser.country=KR -Duser.language=ko -Duser.timezone=Asia/Seoul -Xms1024m -Xmx1024m"
  DB_HOST: "192.168.2.231"
  DB_PORT: "13306"
  DB_NAME: finetrace


---


apiVersion: v1
kind: ConfigMap
metadata:
  namespace: finetrace
  name: scheduler-configmap
data:
  SPRING_PROFILES_ACTIVE: dev
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8 -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Duser.country=KR -Duser.language=ko -Duser.timezone=Asia/Seoul -Xms512m -Xmx512m"
  DB_HOST: "192.168.2.231"
  DB_PORT: "13306"
  DB_NAME: finetrace


---


apiVersion: v1
kind: ConfigMap
metadata:
  namespace: finetrace
  name: alert-configmap
data:
  SPRING_PROFILES_ACTIVE: dev
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8 -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Duser.country=KR -Duser.language=ko -Duser.timezone=Asia/Seoul -Xms512m -Xmx512m"
  DB_HOST: "192.168.2.231"
  DB_PORT: "13306"
  DB_NAME: finetrace


---


apiVersion: v1
kind: Secret
metadata:
  namespace: finetrace
  name: finetrace-secret
data:
  DB_USERNAME: cm9vdA== # root
  DB_PASSWORD: ZnQ0dSEwMDc= # ft4u!007
  #DB_PASSWORD: SXRtc2c0dSE= # Itmsg4u!
  #DB_PASSWORD: RmluZXRyYWNlNHUh # Finetrace4u!
